"""Initial models

Revision ID: 131383e4170c
Revises: 
Create Date: 2025-05-27 14:46:39.486262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '131383e4170c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llmproviderconfig',
    sa.Column('prov_id', sa.Integer(), nullable=False),
    sa.Column('prov_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prov_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prov_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prov_default_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prov_params', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prov_created_at', sa.DateTime(), nullable=False),
    sa.Column('prov_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('prov_id')
    )
    op.create_table('prompttemplate',
    sa.Column('templ_id', sa.Integer(), nullable=False),
    sa.Column('templ_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('templ_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('templ_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('templ_created_at', sa.DateTime(), nullable=False),
    sa.Column('templ_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('templ_id')
    )
    op.create_table('model',
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_provider_id', sa.Integer(), nullable=False),
    sa.Column('model_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_created_at', sa.DateTime(), nullable=False),
    sa.Column('model_updated_at', sa.DateTime(), nullable=False),
    sa.Column('model_params', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['model_provider_id'], ['llmproviderconfig.prov_id'], ),
    sa.PrimaryKeyConstraint('model_name')
    )
    op.create_table('workspace',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('work_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_default_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_created_at', sa.DateTime(), nullable=False),
    sa.Column('work_updated_at', sa.DateTime(), nullable=False),
    sa.Column('work_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['work_default_model'], ['llmproviderconfig.prov_id'], ),
    sa.PrimaryKeyConstraint('work_id')
    )
    op.create_table('message',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('msg_workspace_id', sa.Integer(), nullable=False),
    sa.Column('msg_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('msg_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('msg_created_at', sa.DateTime(), nullable=False),
    sa.Column('msg_updated_at', sa.DateTime(), nullable=True),
    sa.Column('msg_parent_id', sa.Integer(), nullable=True),
    sa.Column('msg_token_count', sa.Integer(), nullable=True),
    sa.Column('msg_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['msg_parent_id'], ['message.msg_id'], ),
    sa.ForeignKeyConstraint(['msg_workspace_id'], ['workspace.work_id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('setting',
    sa.Column('setting_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setting_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setting_workspace_id', sa.Integer(), nullable=True),
    sa.Column('setting_created_at', sa.DateTime(), nullable=False),
    sa.Column('setting_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['setting_workspace_id'], ['workspace.work_id'], ),
    sa.PrimaryKeyConstraint('setting_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    op.drop_table('message')
    op.drop_table('workspace')
    op.drop_table('model')
    op.drop_table('prompttemplate')
    op.drop_table('llmproviderconfig')
    # ### end Alembic commands ###
