"""Add is_available and last_checked to Model

Revision ID: f608934696fd
Revises: 131383e4170c
Create Date: 2025-07-27 21:58:32.460393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f608934696fd'
down_revision: Union[str, None] = '131383e4170c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('is_available', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('model', sa.Column('last_checked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'last_checked')
    op.drop_column('model', 'is_available')
    # ### end Alembic commands ###
